import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const colors = {
  primary: "#f59e0b",
  dark: "#1c1917",
  red: "#ef4444",
  muted: "#78716c",
  border: "#e7e5e4",
  bg: "#fffcf7",
  white: "#ffffff",
};

const styles = StyleSheet.create({
  page: { backgroundColor: colors.bg, padding: 36, fontFamily: "Helvetica", fontSize: 9 },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20, paddingBottom: 16, borderBottom: `2px solid ${colors.primary}` },
  shopName: { fontSize: 18, fontFamily: "Helvetica-Bold", color: colors.dark, marginBottom: 3 },
  shopSub: { fontSize: 8, color: colors.muted, marginBottom: 1 },
  reportTitle: { fontSize: 12, fontFamily: "Helvetica-Bold", color: colors.red, textAlign: "right" },
  reportMeta: { fontSize: 7.5, color: colors.muted, textAlign: "right", marginTop: 2 },
  summaryRow: { flexDirection: "row", gap: 8, marginBottom: 20 },
  summaryCard: { flex: 1, backgroundColor: colors.white, borderRadius: 6, padding: 10, border: `1px solid ${colors.border}` },
  summaryLabel: { fontSize: 7, color: colors.muted, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4 },
  summaryValue: { fontSize: 14, fontFamily: "Helvetica-Bold", color: colors.dark },
  summaryValueRed: { fontSize: 14, fontFamily: "Helvetica-Bold", color: colors.red },
  tableHeader: { flexDirection: "row", backgroundColor: colors.dark, padding: "6 8", borderRadius: 4, marginBottom: 2 },
  tableHeaderText: { fontSize: 7, fontFamily: "Helvetica-Bold", color: colors.white, textTransform: "uppercase", letterSpacing: 0.5 },
  tableRow: { flexDirection: "row", borderBottom: `1px solid ${colors.border}`, padding: "7 8", alignItems: "center" },
  tableRowAlt: { flexDirection: "row", borderBottom: `1px solid ${colors.border}`, padding: "7 8", alignItems: "center", backgroundColor: colors.white },
  cell: { fontSize: 8, color: colors.dark },
  cellMuted: { fontSize: 8, color: colors.muted },
  cellRed: { fontSize: 8, fontFamily: "Helvetica-Bold", color: colors.red },
  totalRow: { flexDirection: "row", backgroundColor: "#fef2f2", padding: "8 8", borderRadius: 4, marginTop: 4, border: `1px solid #fecaca` },
  totalLabel: { fontSize: 9, fontFamily: "Helvetica-Bold", color: colors.red, flex: 1 },
  totalValue: { fontSize: 11, fontFamily: "Helvetica-Bold", color: colors.red },
  sectionTitle: { fontSize: 10, fontFamily: "Helvetica-Bold", color: colors.dark, marginBottom: 8, marginTop: 16, textTransform: "uppercase", letterSpacing: 0.5 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, flexDirection: "row", justifyContent: "space-between", borderTop: `1px solid ${colors.border}`, paddingTop: 8 },
  footerText: { fontSize: 7, color: colors.muted },
});

interface Props {
  expenses: any[];
  period: string;
  shopName: string;
  total: number;
  generatedBy: string;
  formatTZS: (n: number) => string;
  isSw?: boolean;
}

export function ExpensesPDF({ expenses, period, shopName, total, generatedBy, formatTZS, isSw = true }: Props) {
  const local = (sw: string, en: string) => (isSw ? sw : en);
  const today = new Date().toLocaleDateString(isSw ? "sw" : "en", { day: "numeric", month: "long", year: "numeric" });
  const avg = expenses.length > 0 ? Math.round(total / expenses.length) : 0;
  const largest = expenses.length > 0 ? Math.max(...expenses.map(e => e.amount)) : 0;

  // Category totals
  const catMap = new Map<string, number>();
  expenses.forEach(e => catMap.set(e.category, (catMap.get(e.category) || 0) + e.amount));
  const topCats = Array.from(catMap.entries()).sort((a, b) => b[1] - a[1]).slice(0, 5);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.shopName}>{shopName}</Text>
            <Text style={styles.shopSub}>{local("Ripoti ya Matumizi", "Expenses Report")} — {period}</Text>
            <Text style={styles.shopSub}>{local("Tarehe:", "Date:")} {today}</Text>
          </View>
          <View>
            <Text style={styles.reportTitle}>{local("RIPOTI YA MATUMIZI", "EXPENSES REPORT")}</Text>
            <Text style={styles.reportMeta}>{local("Imetolewa na:", "Generated by:")} {generatedBy}</Text>
            <Text style={styles.reportMeta}>{today}</Text>
          </View>
        </View>

        {/* Summary Cards */}
        <View style={styles.summaryRow}>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>{local("Jumla ya Matumizi", "Total Expenses")}</Text>
            <Text style={styles.summaryValueRed}>{formatTZS(total)}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>{local("Idadi ya Rekodi", "Total Records")}</Text>
            <Text style={styles.summaryValue}>{expenses.length}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>{local("Wastani kwa Rekodi", "Average per Record")}</Text>
            <Text style={styles.summaryValue}>{formatTZS(avg)}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>{local("Matumizi Makubwa", "Largest Expense")}</Text>
            <Text style={styles.summaryValueRed}>{formatTZS(largest)}</Text>
          </View>
        </View>

        {/* Top Categories */}
        {topCats.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>{local("Makundi Makubwa", "Top Categories")}</Text>
            <View style={styles.summaryRow}>
              {topCats.map(([cat, amt]) => (
                <View key={cat} style={styles.summaryCard}>
                  <Text style={styles.summaryLabel}>{cat}</Text>
                  <Text style={styles.summaryValue}>{formatTZS(amt)}</Text>
                  <Text style={[styles.cellMuted, { marginTop: 2 }]}>
                    {total > 0 ? Math.round((amt / total) * 100) : 0}%
                  </Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Transactions Table */}
        <Text style={styles.sectionTitle}>{local("Orodha ya Matumizi", "Expense Records")}</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderText, { flex: 1.2 }]}>{local("Tarehe", "Date")}</Text>
          <Text style={[styles.tableHeaderText, { flex: 2.5 }]}>{local("Maelezo", "Description")}</Text>
          <Text style={[styles.tableHeaderText, { flex: 1.5 }]}>{local("Kundi", "Category")}</Text>
          <Text style={[styles.tableHeaderText, { flex: 1.2 }]}>{local("Lipa kwa", "Paid to")}</Text>
          <Text style={[styles.tableHeaderText, { flex: 1.2 }]}>{local("Njia", "Method")}</Text>
          <Text style={[styles.tableHeaderText, { flex: 1.2, textAlign: "right" }]}>{local("Kiasi", "Amount")}</Text>
        </View>

        {expenses.map((e, i) => (
          <View key={e.id} style={i % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
            <Text style={[styles.cellMuted, { flex: 1.2 }]}>{e.date}</Text>
            <Text style={[styles.cell, { flex: 2.5 }]}>{e.description}</Text>
            <Text style={[styles.cellMuted, { flex: 1.5 }]}>{e.category}</Text>
            <Text style={[styles.cellMuted, { flex: 1.2 }]}>{e.paidTo || "—"}</Text>
            <Text style={[styles.cellMuted, { flex: 1.2 }]}>{e.paymentMethod}</Text>
            <Text style={[styles.cellRed, { flex: 1.2, textAlign: "right" }]}>{formatTZS(e.amount)}</Text>
          </View>
        ))}

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>{local("JUMLA YA MATUMIZI", "TOTAL EXPENSES")}</Text>
          <Text style={styles.totalValue}>{formatTZS(total)}</Text>
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Twende Duka · {shopName}</Text>
          <Text style={styles.footerText}>{local("Imetolewa:", "Generated:")} {today} · {generatedBy}</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `${local("Ukurasa", "Page")} ${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
